[dependencies]
solana-client = "1.10.34"
solana-sdk = "1.10.34"
tokio = { version = "1", features = ["full"] }
egui = "0.16"
eframe = "0.16"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
